workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "ios/YourApp.xcworkspace"
        XCODE_SCHEME: "YourApp"
    scripts:
      - npm install
      - cd ios
      - pod install
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: 6fYVt-dNqOfStKdBUbdQXETd1Wo2M7-9S2RaFumX3kQ
        submit_to_testflight: true