export const brandList = {
  status: 'Success',
  medialink: 'https://tinynote.in/ofo/public/assests/proimg/',
  data: [
    {
      b_id: '1',
      name: 'FreshCo',
      email: 'freshco@tnh.com',
      phone: '0123456789',
      postal: '12345',
      province: 'Province',
      city: 'City',
      address:
        '                                                \tAddress                                                ',
      logo: 'freshco.png',
      // logo: require('../assets/brand-list/freshco.png'),
      barcode: '',
      txtcode: '',
      date: '2024-11-27 14:50:21',
    },
    {
      b_id: '2',
      name: 'Bigbox outlet',
      email: 'bigbox@tnh.com',
      phone: '0123456789',
      postal: '12345',
      province: 'Province',
      city: 'City',
      address:
        '                                                \tAddress                                                ',
      logo: 'bigbox outlet.jpg',
      // logo: require('../assets/brand-list/bigbox outlet.jpg'),
      barcode: '',
      txtcode: '',
      date: '2024-11-27 14:51:48',
    },
    {
      b_id: '3',
      name: 'save on foods',
      email: 'saveonfoods@tnh.com',
      phone: '0123456789',
      postal: '12345',
      province: 'Province',
      city: 'City',
      address:
        '                                                \taddress here                                                ',
      logo: 'save on foods.png',
      // logo: require('../assets/brand-list/save on foods.png'),
      barcode: '',
      txtcode: '',
      date: '2024-11-28 14:53:08',
    },
    {
      b_id: '4',
      name: 'source office furniture',
      email: 'source@tnh.com',
      phone: '0123456789',
      postal: '12345',
      province: 'Province',
      city: 'City',
      address:
        '                                                \taddr here                                                ',
      logo: 'source office furniture.jpg',
      // logo: require('../assets/brand-list/source office furniture.jpg'),
      barcode: '',
      txtcode: '',
      date: '2024-11-28 14:54:32',
    },
    {
      b_id: '5',
      name: 'wallmart',
      email: 'wallmart@tnh.com',
      phone: '0123456789',
      postal: '12345',
      province: 'Province',
      city: 'City',
      address:
        '                                                \taddress here                                                ',
      logo: 'wallmart.png',
      // logo: require('../assets/brand-list/wallmart.png'),
      barcode: '',
      txtcode: '',
      date: '2024-11-28 14:55:41',
    },
    {
      b_id: '6',
      name: 'wellwise',
      email: 'wellwise@tnh.com',
      phone: '0123456789',
      postal: '12345',
      province: 'Province',
      city: 'City',
      address:
        '                                                \tAddress                                                ',
      logo: 'wellwise.jpg',
      // logo: require('../assets/brand-list/wellwise.jpg'),
      barcode: '',
      txtcode: '',
      date: '2024-11-29 14:57:01',
    },
    {
      b_id: '7',
      name: 'pharma choice',
      email: 'pharmac@tnh.com',
      phone: '0123456789',
      postal: '12345',
      province: 'Province',
      city: 'City',
      address:
        '                                                \taddress here                                                ',
      logo: 'pharma choice.jpg',
      // logo: require('../assets/brand-list/pharma choice.jpg'),
      barcode: '',
      txtcode: '',
      date: '2024-11-29 14:58:03',
    },
    {
      b_id: '8',
      name: 'The Home Depot',
      email: 'TheHomeDepot@tnh.com',
      phone: '0123456789',
      postal: '12345',
      province: 'Province',
      city: 'City',
      address:
        '                                                \taddr here                                                ',
      logo: 'TheHomeDepot.png',
      // logo: require('../assets/brand-list/TheHomeDepot.png'),
      barcode: '',
      txtcode: '',
      date: '2024-11-29 14:59:45',
    },
    {
      b_id: '9',
      name: 'real canadian superstore',
      email: 'realcs@tnh.com',
      phone: '0123456789',
      postal: '12345',
      province: 'Province',
      city: 'City',
      address:
        '                                                \tAddress                                                ',
      logo: 'real canadian superstore.png',
      // logo: require('../assets/brand-list/real canadian superstore.png'),
      barcode: '',
      txtcode: '',
      date: '2024-11-30 15:00:59',
    },
    {
      b_id: '10',
      name: 'safeway',
      email: 'safeway@tnh.com',
      phone: '0123456789',
      postal: '12345',
      province: 'Province',
      city: 'City',
      address:
        '                                                \tAddress                                                ',
      logo: 'safeway.png',
      // logo: require('../assets/brand-list/safeway.png'),
      barcode: '',
      txtcode: '',
      date: '2024-11-30 15:01:55',
    },
    {
      b_id: '11',
      name: 'adidas',
      email: 'adidas@tnh.com',
      phone: '0123456789',
      postal: '12345',
      province: 'Province',
      city: 'City',
      address: 'address here                                                ',
      logo: 'adidas.png',
      // logo: require('../assets/brand-list/adidas.png'),
      barcode: '',
      txtcode: '',
      date: '2024-11-30 15:03:20',
    },
    {
      b_id: '12',
      name: 'nike',
      email: 'nike@tnh.com',
      phone: '0123456789',
      postal: '12345',
      province: 'Province',
      city: 'City',
      address:
        '                                                \taddr here                                                ',
      logo: 'nike.png',
      // logo: require('../assets/brand-list/nike.png'),
      barcode: '',
      txtcode: '',
      date: '2024-12-01 15:04:11',
    },
    {
      b_id: '13',
      name: 'pepsi',
      email: 'pepsi@tnh.com',
      phone: '0123456789',
      postal: '12345',
      province: 'Province',
      city: 'City',
      address:
        '                                                \tAddress                                                ',
      logo: 'pepsi.png',
      // logo: require('../assets/brand-list/pepsi.png'),
      barcode: '',
      txtcode: '',
      date: '2024-12-01 15:05:00',
    },
  ],
};

export const Categories = {
  status: 'Success',
  data: [
    {
      c_id: '13',
      c_name: 'stationary',
      status: '',
      date: '0000-00-00 00:00:00',
    },
    {
      c_id: '12',
      c_name: 'Computers',
      status: '',
      date: '0000-00-00 00:00:00',
    },
    {
      c_id: '11',
      c_name: 'Mobiles',
      status: '',
      date: '0000-00-00 00:00:00',
    },
    {
      c_id: '10',
      c_name: 'Health care',
      status: '',
      date: '0000-00-00 00:00:00',
    },
    {
      c_id: '9',
      c_name: 'Pets',
      status: '',
      date: '0000-00-00 00:00:00',
    },
    {
      c_id: '8',
      c_name: 'Sports',
      status: '',
      date: '0000-00-00 00:00:00',
    },
    {
      c_id: '7',
      c_name: 'Fashion',
      status: '',
      date: '0000-00-00 00:00:00',
    },
    {
      c_id: '6',
      c_name: 'Electronics',
      status: '',
      date: '0000-00-00 00:00:00',
    },
    {
      c_id: '5',
      c_name: 'Gerneral',
      status: '',
      date: '0000-00-00 00:00:00',
    },
    {
      c_id: '4',
      c_name: 'Home and garden',
      status: '',
      date: '0000-00-00 00:00:00',
    },
    {
      c_id: '3',
      c_name: 'Groceries',
      status: '',
      date: '0000-00-00 00:00:00',
    },
    {
      c_id: '2',
      c_name: 'Black Friday',
      status: '',
      date: '0000-00-00 00:00:00',
    },
    {
      c_id: '1',
      c_name: 'All Circulars',
      status: '',
      date: '0000-00-00 00:00:00',
    },
  ],
};

export const flyersData = [
  {
    f_id: '11',
    b_id: '1',
    s_id: '3',
    c_id: '1',
    name: 'save on foods2',
    s_date: '2024-12-01',
    e_date: '2024-12-20',
    special: '1',
    // file: '6_2.jpg',
    file: require('../assets/flyers/6_2.jpg'),
    // file: require('../assets/special/2_1.jpg'),
    brand_name: 'FreshCo',
    brand_logo: 'freshco.png',
  },
  {
    f_id: '9',
    b_id: '1',
    s_id: '3',
    c_id: '1',
    name: 'Safeways1',
    s_date: '2024-12-06',
    e_date: '2024-12-15',
    special: '1',
    // file: '4_1.jpg',
    file: require('../assets/flyers/4_1.jpg'),
    brand_name: 'FreshCo',
    brand_logo: 'freshco.png',
  },
  {
    f_id: '8',
    b_id: '15',
    s_id: '5',
    c_id: '13',
    name: 'No Frills',
    s_date: '2024-12-06',
    e_date: '2024-12-15',
    special: '1',
    // file: '1_2.jpg',
    file: require('../assets/flyers/1_2.jpg'),
    brand_name: 'teststores',
    brand_logo: '6290860e72d1e.jpg',
  },
  {
    f_id: '7',
    b_id: '2',
    s_id: '4',
    c_id: '1',
    name: 'Safeway',
    s_date: '2024-12-06',
    e_date: '2024-12-15',
    special: '0',
    // file: '7.jpg',
    file: require('../assets/flyers/7.jpg'),
    brand_name: 'Bigbox outlet',
    brand_logo: 'bigbox outlet.jpg',
  },
  {
    f_id: '6',
    b_id: '6',
    s_id: '5',
    c_id: '8',
    name: 'The Home Depot',
    s_date: '2024-12-05',
    e_date: '2024-12-13',
    special: '1',
    // file: '6.jpg',
    file: require('../assets/flyers/6.jpg'),
    brand_name: 'wellwise',
    brand_logo: 'wellwise.jpg',
  },
  {
    f_id: '5',
    b_id: '5',
    s_id: '1',
    c_id: '7',
    name: 'well wise',
    s_date: '2024-12-04',
    e_date: '2024-12-12',
    special: '0',
    // file: '5_2.jpg',
    file: require('../assets/flyers/5_2.jpg'),
    brand_name: 'wallmart',
    brand_logo: 'wallmart.png',
  },
  {
    f_id: '4',
    b_id: '4',
    s_id: '4',
    c_id: '6',
    name: 'wallmart',
    s_date: '2024-12-03',
    e_date: '2024-12-13',
    special: '1',
    // file: '4.jpg',
    file: require('../assets/flyers/4_1.jpg'),
    brand_name: 'source office furniture',
    brand_logo: 'source office furniture.jpg',
  },
  {
    f_id: '3',
    b_id: '3',
    s_id: '1',
    c_id: '4',
    name: 'save on foods',
    s_date: '2024-12-02',
    e_date: '2024-12-12',
    special: '0',
    // file: '3_1.jpg',
    file: require('../assets/flyers/3_1.jpg'),
    brand_name: 'save on foods',
    brand_logo: 'save on foods.png',
  },
  {
    f_id: '2',
    b_id: '2',
    s_id: '3',
    c_id: '3',
    name: 'Bigbox outlet',
    s_date: '2024-12-01',
    e_date: '2024-12-11',
    special: '1',
    // file: '2_1.jpg',
    file: require('../assets/flyers/2_1.jpg'),
    brand_name: 'Bigbox outlet',
    brand_logo: 'bigbox outlet.jpg',
  },
  {
    f_id: '1',
    b_id: '1',
    s_id: '1',
    c_id: '2',
    name: 'FreshCo',
    s_date: '2024-11-30',
    e_date: '2024-12-10',
    special: '0',
    // file: '1_1.jpg',
    file: require('../assets/flyers/1_1.jpg'),
    brand_name: 'FreshCo',
    brand_logo: 'freshco.png',
  },
];

export const specialEventsData = {
  status: 'Success',
  medialink: 'https://tinynote.in/ofo/public/assests/proimg/',
  data: [
    {
      f_id: '2',
      b_id: '2',
      s_id: '3',
      c_id: '3',
      name: 'Bigbox outlet',
      s_date: '2024-12-01',
      e_date: '2024-12-11',
      special: '1',
      // file: '2_1.jpg',
      file: require('../assets/special/2_1.jpg'),
      brand_name: 'Bigbox outlet',
      brand_logo: 'bigbox outlet.jpg',
    },
    {
      f_id: '4',
      b_id: '4',
      s_id: '4',
      c_id: '6',
      name: 'wallmart',
      s_date: '2024-12-03',
      e_date: '2024-12-13',
      special: '1',
      // file: '4.jpg',
      file: require('../assets/special/4.jpg'),
      brand_name: 'source office furniture',
      brand_logo: 'source office furniture.jpg',
    },
    {
      f_id: '6',
      b_id: '6',
      s_id: '5',
      c_id: '8',
      name: 'The Home Depot',
      s_date: '2024-12-05',
      e_date: '2024-12-13',
      special: '1',
      // file: '6.jpg',
      file: require('../assets/special/6.jpg'),
      brand_name: 'wellwise',
      brand_logo: 'wellwise.jpg',
    },
    {
      f_id: '8',
      b_id: '15',
      s_id: '5',
      c_id: '10',
      name: 'No Frills',
      s_date: '2024-12-06',
      e_date: '2024-12-15',
      special: '1',
      // file: '1_2.jpg',
      file: require('../assets/special/1_2.jpg'),
      brand_name: 'teststores',
      brand_logo: '6290860e72d1e.jpg',
    },
    {
      f_id: '9',
      b_id: '1',
      s_id: '3',
      c_id: '11',
      name: 'Safeways1',
      s_date: '2024-12-06',
      e_date: '2024-12-15',
      special: '1',
      // file: '4_1.jpg',
      file: require('../assets/special/4.jpg'),
      brand_name: 'FreshCo',
      brand_logo: 'freshco.png',
    },
    {
      f_id: '11',
      b_id: '1',
      s_id: '3',
      c_id: '11',
      name: 'save on foods2',
      s_date: '2024-12-01',
      e_date: '2024-12-20',
      special: '1',
      // file: '6_2.jpg',
      file: require('../assets/special/6.jpg'),
      brand_name: 'FreshCo',
      brand_logo: 'freshco.png',
    },
  ],
};
